using System;
using System.Collections.Generic;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

public class FactionAssetTests
{
    private readonly List<string> names = new();
    private string NewName()
    {
        string name = "FactionTest" + Guid.NewGuid().ToString("N");
        names.Add(name);
        return name;
    }
    private Faction Source => AssetDatabase.LoadAssetAtPath<Faction>("Assets/Data/Factions/Red/Red.asset");

    [TearDown]
    public void Cleanup()
    {
        // Only folders with names generated by this test are removed.
        foreach (string name in names)
        {
            AssetDatabase.DeleteAsset(FactionAssetUtility.DataFolder(name));
            AssetDatabase.DeleteAsset(FactionAssetUtility.PrefabFolder(name));
        }
        names.Clear();
    }

    [Test]
    public void CreateAndAddPlaceAssetsInTheirCanonicalFolders()
    {
        string name = NewName();
        var faction = FactionAssetUtility.Create(name);
        Assert.That(AssetDatabase.GetAssetPath(faction), Is.EqualTo(FactionAssetUtility.DataFolder(name) + "/" + name + ".asset"));
        Assert.That(AssetDatabase.IsValidFolder(FactionAssetUtility.PrefabFolder(name)), Is.True);
        var source = Source.startingUnit;
        var entry = FactionAssetUtility.AddUnit(faction, source.unitData, source.prefab);
        Assert.That(entry.name, Is.EqualTo(name + " " + source.unitData.name));
        Assert.That(entry.prefab.name, Is.EqualTo(entry.name));
        Assert.That(AssetDatabase.GetAssetPath(entry.prefab), Is.EqualTo(FactionAssetUtility.PrefabFolder(name) + "/" + entry.name + ".prefab"));
        Assert.That(entry.unitData, Is.EqualTo(source.unitData));
        FactionAssetUtility.SetCity(faction, Source.cityPrefab);
        Assert.That(faction.cityPrefab.name, Is.EqualTo(name + " City"));
        Assert.That(faction.cityPrefab, Is.Not.EqualTo(Source.cityPrefab));
        Assert.Throws<InvalidOperationException>(() => FactionAssetUtility.AddUnit(faction, source.unitData, source.prefab));
    }

    [Test]
    public void DuplicateCopiesPrefabsAndRewiresRosterWhileSharingStats()
    {
        string name = NewName();
        var source = Source;
        var copy = FactionAssetUtility.Create(name, source);
        Assert.That(copy.availableUnits.Length, Is.EqualTo(source.availableUnits.Length));
        for (int i = 0; i < copy.availableUnits.Length; i++)
        {
            var entry = copy.availableUnits[i];
            Assert.That(entry.faction, Is.EqualTo(copy));
            Assert.That(entry.unitData, Is.EqualTo(source.availableUnits[i].unitData));
            Assert.That(entry.prefab, Is.Not.EqualTo(source.availableUnits[i].prefab));
            Assert.That(entry.name, Is.EqualTo(name + " " + entry.unitData.name));
            Assert.That(entry.prefab.name, Is.EqualTo(entry.name));
            Assert.That(AssetDatabase.GetAssetPath(entry), Is.EqualTo(FactionAssetUtility.DataFolder(name) + "/" + entry.name + ".asset"));
            Assert.That(AssetDatabase.GetAssetPath(entry.prefab), Is.EqualTo(FactionAssetUtility.PrefabFolder(name) + "/" + entry.name + ".prefab"));
        }
        Assert.That(copy.startingUnit, Is.EqualTo(copy.availableUnits[Array.IndexOf(source.availableUnits, source.startingUnit)]));
        Assert.That(copy.cityPrefab.name, Is.EqualTo(name + " City"));
        Assert.That(copy.cityPrefab, Is.Not.EqualTo(source.cityPrefab));
        Assert.That(copy.startingUnlockedTech, Is.EqualTo(source.startingUnlockedTech));
    }

    [TestCase(true)]
    [TestCase(false)]
    public void RenamePreservesGuidsAndRespectsRelatedNames(bool related)
    {
        string oldName = NewName(), newName = NewName();
        var faction = FactionAssetUtility.Create(oldName, Source);
        var entry = faction.startingUnit;
        string oldUnitName = entry.name;
        string factionGuid = GuidOf(faction), unitGuid = GuidOf(entry), prefabGuid = GuidOf(entry.prefab), cityGuid = GuidOf(faction.cityPrefab);
        string dataFolderGuid = AssetDatabase.AssetPathToGUID(FactionAssetUtility.DataFolder(oldName));
        string prefabFolderGuid = AssetDatabase.AssetPathToGUID(FactionAssetUtility.PrefabFolder(oldName));
        FactionAssetUtility.Rename(faction, newName, related);
        Assert.That(faction.name, Is.EqualTo(newName));
        Assert.That(entry.name, Is.EqualTo(related ? newName + " " + entry.unitData.name : oldUnitName));
        Assert.That(entry.prefab.name, Is.EqualTo(entry.name));
        Assert.That(faction.cityPrefab.name, Is.EqualTo((related ? newName : oldName) + " City"));
        Assert.That(GuidOf(faction), Is.EqualTo(factionGuid));
        Assert.That(GuidOf(entry), Is.EqualTo(unitGuid));
        Assert.That(GuidOf(entry.prefab), Is.EqualTo(prefabGuid));
        Assert.That(GuidOf(faction.cityPrefab), Is.EqualTo(cityGuid));
        Assert.That(AssetDatabase.AssetPathToGUID(FactionAssetUtility.DataFolder(newName)), Is.EqualTo(dataFolderGuid));
        Assert.That(AssetDatabase.AssetPathToGUID(FactionAssetUtility.PrefabFolder(newName)), Is.EqualTo(prefabFolderGuid));
        Assert.That(AssetDatabase.IsValidFolder(FactionAssetUtility.DataFolder(oldName)), Is.False);
        Assert.That(AssetDatabase.GetAssetPath(entry.prefab), Does.StartWith(FactionAssetUtility.PrefabFolder(newName) + "/"));
    }

    [Test]
    public void ConflictingAndInvalidNamesLeaveSourceUnchanged()
    {
        string first = NewName(), second = NewName();
        var source = FactionAssetUtility.Create(first);
        FactionAssetUtility.Create(second);
        Assert.Throws<InvalidOperationException>(() => FactionAssetUtility.Rename(source, second, true));
        Assert.Throws<InvalidOperationException>(() => FactionAssetUtility.Create(first));
        Assert.Throws<InvalidOperationException>(() => FactionAssetUtility.Create("../Escape"));
        Assert.That(source.name, Is.EqualTo(first));
        Assert.That(AssetDatabase.IsValidFolder(FactionAssetUtility.DataFolder(first)), Is.True);
    }

    [Test]
    public void CaseOnlyRenamePreservesFolderGuid()
    {
        string name = NewName();
        var faction = FactionAssetUtility.Create(name);
        string guid = GuidOf(faction);
        string lower = name.ToLowerInvariant();
        names.Add(lower);
        FactionAssetUtility.Rename(faction, lower, true);
        Assert.That(AssetDatabase.GetAssetPath(faction), Is.EqualTo(FactionAssetUtility.DataFolder(lower) + "/" + lower + ".asset"));
        Assert.That(GuidOf(faction), Is.EqualTo(guid));
    }

    private static string GuidOf(UnityEngine.Object asset) => AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(asset));
}
